### ISSUE TITLE
OSX: capture.c:26:10: fatal error: 'netpacket/packet.h' file not found

### ISSUE THREAD

**Issue by hanksudo** [br101/horst#5]
I try to compile on OSX 10.10, but can't work.

Seems I miss some header file, any suggestion?

thanks.

**Comment by br101** [comment]
Could you try with the latest version and `make PCAP=1 WEXT=0 LIBNL=0`?

**Comment by br101** [comment]
This error should be solved by passing PCAP=1, and I close this issue as it is essentially a duplicate of #34 (OSX build)
