### ISSUE TITLE
cd49bed fails to build on OS X 10.11.6

### ISSUE THREAD

**Issue by aaaaalbert** [br101/horst#53]
I'm trying to build cd49bed3a93ec57744726e86c93caabba43d6545 (of July 29) on a Mac OS X 10.11.6 machine. This causes a build error, see below. Let me know if I can try and help debug the problem, or if there is any additional information about the build environment that you need.

```
$ make OSX=1
gcc -MM -I. conf_options.c control.c display-channel.c display-essid.c display-filter.c display-help.c display-history.c display-main.c display-spectrum.c display-statistics.c display.c essid.c hutil.c ieee80211_duration.c listsort.c main.c network.c protocol_parser.c >.objdeps.mk
conf_options.c:25:10: fatal error: 'uwifi/util.h' file not found
#include <uwifi/util.h>
         ^
1 error generated.
In file included from control.c:27:
./main.h:27:10: fatal error: 'ccan/list/list.h' file not found
#include <ccan/list/list.h>
         ^
1 error generated.
In file included from display-channel.c:25:
./main.h:27:10: fatal error: 'ccan/list/list.h' file not found
#include <ccan/list/list.h>
         ^
1 error generated.
display-essid.c:24:10: fatal error: 'uwifi/node.h' file not found
#include <uwifi/node.h>
         ^
1 error generated.
display-filter.c:24:10: fatal error: 'uwifi/wlan_util.h' file not found
#include <uwifi/wlan_util.h>
         ^
1 error generated.
display-help.c:24:10: fatal error: 'uwifi/wlan_util.h' file not found
#include <uwifi/wlan_util.h>
         ^
1 error generated.
display-history.c:24:10: fatal error: 'uwifi/util.h' file not found
#include <uwifi/util.h>
         ^
1 error generated.
display-main.c:25:10: fatal error: 'uwifi/wlan80211.h' file not found
#include <uwifi/wlan80211.h>
         ^
1 error generated.
display-spectrum.c:24:10: fatal error: 'uwifi/util.h' file not found
#include <uwifi/util.h>
         ^
1 error generated.
display-statistics.c:24:10: fatal error: 'uwifi/wlan_util.h' file not found
#include <uwifi/wlan_util.h>
         ^
1 error generated.
display.c:29:10: fatal error: 'uwifi/wlan80211.h' file not found
#include <uwifi/wlan80211.h>
         ^
1 error generated.
essid.c:23:10: fatal error: 'uwifi/wlan80211.h' file not found
#include <uwifi/wlan80211.h>
         ^
1 error generated.
ieee80211_duration.c:19:10: fatal error: 'uwifi/platform.h' file not found
#include <uwifi/platform.h>
         ^
1 error generated.
listsort.c:46:10: fatal error: 'ccan/list/list.h' file not found
#include <ccan/list/list.h>
         ^
1 error generated.
main.c:32:10: fatal error: 'uwifi/packet_sock.h' file not found
#include <uwifi/packet_sock.h>
         ^
1 error generated.
network.c:30:10: fatal error: 'uwifi/util.h' file not found
#include <uwifi/util.h>
         ^
1 error generated.
protocol_parser.c:28:10: fatal error: 'uwifi/raw_parser.h' file not found
#include <uwifi/raw_parser.h>
         ^
1 error generated.
echo '-std=gnu99 -Wall -Wextra -g -I.' | cmp -s - .buildflags || echo '-std=gnu99 -Wall -Wextra -g -I.' > .buildflags
cc -std=gnu99 -Wall -Wextra -g -I.   -c -o conf_options.o conf_options.c
conf_options.c:25:10: fatal error: 'uwifi/util.h' file not found
#include <uwifi/util.h>
         ^
1 error generated.
make: *** [conf_options.o] Error 1
```

**Comment by Duncaen** [comment]
Same as #52.

**Comment by aaaaalbert** [comment]
@Duncaen, thanks for pointing that out! I had missed that issue.

@br101, how would you like me to proceed with this? I guess adding a line to the README to mention the `stable` branch and/or potential problems on `master` would be in order. I can send a PR if you like.

**Comment by br101** [comment]
I added libuwifi as a git submodule and updated the readme in bad969583b8f2a7a5c641d704c98051f92fa477c. If there are things missing or uncertainties please let me know.

OSX support on master with libuwifi is broken. I need some time to improve the structure for different OS and PCAP. Pull requests always welcome.

**Comment by aaaaalbert** [comment]
Thank you @br101, I think bad9695 adds a clear statement to the README as to what to do (and what not). I'm closing this issue.
