### ISSUE TITLE
horst wont compile on LEDE

### ISSUE THREAD

**Issue by FreifunkUFO** [br101/horst#64]
i often compile LEDE/openwrt by myself. with lede-trunk from yesterday horst has errors.
error messages are here: https://plan.leipzig.freifunk.net/issues/373

**Comment by RussellSenior** [comment]
I bisected this to lede commit 6a902108a8da710f5359db82bd8295eed571f0de, an update of ncurses.  Not clear why we are getting the error.

**Comment by RussellSenior** [comment]
Adding: `TARGET_CFLAGS += -D_GNU_SOURCE` to the Makefile seems to fix the build, e.g.:

```
diff --git a/net/horst/Makefile b/net/horst/Makefile
index 1eb7409..2c0b72d 100644
--- a/net/horst/Makefile
+++ b/net/horst/Makefile
@@ -42,6 +42,8 @@ define Package/horst/description
        and especially IBSS (ad-hoc) mode and mesh networks (OLSR).
 endef
 
+TARGET_CFLAGS += -D_GNU_SOURCE
+
 define Package/horst/install
        $(INSTALL_DIR) $(1)/usr/sbin
        $(INSTALL_BIN) $(PKG_BUILD_DIR)/horst $(1)/usr/sbin/

```

**Comment by FreifunkUFO** [comment]
beware, software is used at version 5.0 (instead of master). but trunk (aka v5.1 also doenst work https://github.com/freifunk-leipzig/horst/releases/tag/version-5.1 )
maybe its something with the fortify-headers inside toolchain (v8 on lede, instead of v7, used with openwrt)?


```

In file included from /srv2/lede/lede-20170102/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify/stdlib.h:28:0,
from display-channel.c:22:
/srv2/lede/lede-20170102/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify/string.h:142:13: error: 'mempcpy' undeclared here (not in a function)
FORTIFY_FN(mempcpy) void mempcpy(void *d, const void *_s, size_t _n)
^
/srv2/lede/lede-20170102/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify/fortify-headers.h:20:40: note: in definition of macro '_FORTIFY_ORIG'
#define _FORTIFY_ORIG(p,fn) __typeof(fn) orig##fn _asm(_FORTIFY_STR(p) #fn)
^
/srv2/lede/lede-20170102/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify/string.h:142:1: note: in expansion of macro '_FORTIFY_FN'
_FORTIFY_FN(mempcpy) void *mempcpy(void *d, const void *_s, size_t _n)
^
In file included from ./ccan/str/str.h:5:0,
from ccan/list/list.h:7,
from main.h:27,
from display-channel.c:25:
/srv2/lede/lede-20170102/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify/string.h: In function 'mempcpy':
/srv2/lede/lede-20170102/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify/string.h:149:9: error: called object '_orig_mempcpy' is not a function or function pointer
return _orig_mempcpy(_d, _s, __n);
^
In file included from /srv2/lede/lede-20170102/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify/stdlib.h:28:0,
from display-channel.c:22:
/srv2/lede/lede-20170102/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify/fortify-headers.h:20:44: note: declared here
#define _FORTIFY_ORIG(p,fn) __typeof(fn) orig##fn _asm(_FORTIFY_STR(p) #fn)
^
/srv2/lede/lede-20170102/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify/fortify-headers.h:21:25: note: in expansion of macro '_FORTIFY_ORIG'
#define _FORTIFY_FN(fn) _FORTIFY_ORIG(USER_LABEL_PREFIX,fn); \
^
/srv2/lede/lede-20170102/staging_dir/toolchain-mips_24kc_gcc-5.4.0_musl-1.1.15/include/fortify/string.h:142:1: note: in expansion of macro '_FORTIFY_FN'
_FORTIFY_FN(mempcpy) void *mempcpy(void *_d, const void *__s, size_t __n)
^
<builtin>: recipe for target 'display-channel.o' failed
make3: [display-channel.o] Error 1
make3: Leaving directory '/srv2/lede/lede-20170102/build_dir/target-mips_24kc_musl-1.1.15/horst-5.0'
Makefile:51: recipe for target '/srv2/lede/lede-20170102/build_dir/target-mips_24kc_musl-1.1.15/horst-5.0/.built' failed
make2: [/srv2/lede/lede-20170102/build_dir/target-mips_24kc_musl-1.1.15/horst-5.0/.built] Error 2
make2: Leaving directory '/srv2/lede/lede-20170102/feeds/packages/net/horst'
package/Makefile:133: recipe for target 'package/feeds/packages/horst/compile' failed
make1: [package/feeds/packages/horst/compile] Error 2
make1: Leaving directory '/srv2/lede/lede-20170102'
/srv2/lede/lede-20170102/include/toplevel.mk:197: recipe for target 'package/feeds/packages/horst/compile' failed
make: * [package/feeds/packages/horst/compile] Error 2
```

**Comment by FreifunkUFO** [comment]
oh, @dangowrt wrote:

set
PKG_FORTIFY_SOURCE:=0
in feeds/packages/net/horst/Makefile

and now its compiling

**Comment by FreifunkUFO** [comment]
and (with that build) horst is running :-)

**Comment by RussellSenior** [comment]
with FORTIFY_SOURCE on, I get a: "Trace/breakpoint trap" message, and horst exits.  This seems to imply that fortify thinks horst is doing something dangerous, or violating a bounds or something.  However, I can't tell where.

**Comment by br101** [comment]
fixed
