### ISSUE TITLE
Could not compile on macOS 10.14.4

### ISSUE THREAD

**Issue by MuntashirAkon** [br101/horst#96]
I could not compile the latest release on macOS 10.14.4.

**Log**
```bash
Muntashirs-MBP:horst-5.1 muntashir$ make OSX=1
echo '-std=gnu99 -Wall -Wextra -g -I. -DVERSION=\"5.1\" -DDO_DEBUG -DPCAP' | cmp -s - .buildflags || echo '-std=gnu99 -Wall -Wextra -g -I. -DVERSION=\"5.1\" -DDO_DEBUG -DPCAP' > .buildflags
cc -std=gnu99 -Wall -Wextra -g -I. -DVERSION=\"5.1\" -DDO_DEBUG -DPCAP   -c -o main.o main.c
In file included from main.c:48:
./mach_clock_gettime.h:13:9: warning: 'CLOCK_MONOTONIC' macro redefined
      [-Wmacro-redefined]
#define CLOCK_MONOTONIC 1       /* Per Linux's time.h */
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/time.h:156:9: note: 
      previous definition is here
#define CLOCK_MONOTONIC _CLOCK_MONOTONIC
        ^
In file included from main.c:48:
./mach_clock_gettime.h:14:13: error: typedef redefinition with different types
      ('int' vs 'enum clockid_t')
typedef int clockid_t;          /* Per Linux's types.h, posix_types.h */
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/time.h:171:3: note: 
      previous definition is here
} clockid_t;
  ^
1 warning and 1 error generated.
make: *** [main.o] Error 1
```

**Comment by br101** [comment]
someone with MacOS should take a look on that as I won't be able to do that
